// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw6O8_TTtpIxx4Wa1-oRfUDNPnB__mcCc',
    appId: '1:328063784849:web:fc8d6aa03e1501c9816c30',
    messagingSenderId: '328063784849',
    projectId: 'kweedo-d552a',
    authDomain: 'kweedo-d552a.firebaseapp.com',
    storageBucket: 'kweedo-d552a.appspot.com',
    measurementId: 'G-H7P8T3N5JV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByRt9-98LdVjdaMOz_LLKc-FLJiLaLJ0U',
    appId: '1:328063784849:android:ebe19131299a1037816c30',
    messagingSenderId: '328063784849',
    projectId: 'kweedo-d552a',
    storageBucket: 'kweedo-d552a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuVmSWO0S8hp7GH-OnAwzHfBjCq3JD1O8',
    appId: '1:328063784849:ios:92dd2cd1b9afa071816c30',
    messagingSenderId: '328063784849',
    projectId: 'kweedo-d552a',
    storageBucket: 'kweedo-d552a.appspot.com',
    androidClientId: '328063784849-f6u0rvfsk8ibg22q92idd80jn0bpmk1k.apps.googleusercontent.com',
    iosClientId: '328063784849-jpkph4lfn6ahv00eracplims4psn8efm.apps.googleusercontent.com',
    iosBundleId: 'com.tommymolto.kweedo',
  );
}
